name: OnlineTime
main: Zedstar16\OnlineTime\Main
version: 1.3
api: 3.0.0
load: POSTWORLD
author: Zedstar16
description: Measure time spent online
website: https://github.com/Zedstar16/OnlineTime

commands:
 onlinetime:
  aliases: [ot, otime]
  description: "View how much time you've spent on the server"
  permission: onlinetime

permissions:
 reset.onlinetime:
  default: scorehud
  description: "no reset"
 onlinetime:
  default: false
  description: "top"
